services:
  api:
    build:
      context: .
      target: api
      args:
        DOTNET_VERSION: "8.0"
    ports:
      - "5075:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"

  blazor:
    build:
      context: .
      target: blazor
      args:
        DOTNET_VERSION: "8.0"
    ports:
      - "8000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      # Example for calling API from Web via compose service DNS:
      # API_BASE_URL: "http://api:8080"
    depends_on:
      - api
